CREATE TABLE MedicationOrderAllUclhFactX (
    MedicationOrderAllUclhKey            INTEGER  PRIMARY KEY,
    PatientDurableKey                    INTEGER  REFERENCES PatientDim (DurableKey),
    EncounterKey                         INTEGER  REFERENCES EncounterFact (EncounterKey),
    MedicationKey                        INTEGER  REFERENCES MedicationDim (MedicationKey),
    StartDateKey                         INTEGER,
    OrderedDateKey                       INTEGER,
    EndDateKey                           INTEGER,
    DiscontinuedDateKey                  INTEGER,
    Route                                TEXT,
    MinimumDose                          REAL,
    DoseUnit                             TEXT,
    Quantity                             REAL,
    QuantityUnit                         TEXT,
    NumberOfDoses                        INTEGER,
    Frequency                            TEXT,
    DiscontinueReason                    TEXT,
    OrderClass                           TEXT,
    IsOutpatientMode                     INTEGER,
    Source                               TEXT,
    Mode                                 TEXT,
    MedicationOrderEpicId                INTEGER,
    Sig                                  TEXT,
    DaysSupply                           REAL
);
